apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database
spec:
  resources:
    requests:
      storage: 1Gi
#  selector:
#    matchLabels:
#      volume: my-volume
  accessModes:
    - ReadWriteOnce

